language: perl
sudo: required
install:
  - cpanm --installdeps --notest . || find /home/travis -name build.log -exec tail -n 10000 /dev/null {} \;
  - sudo apt-get install devscripts
script: make deb
