language: perl
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y devscripts   # provides: debuild
  - gem install package_cloud
# XXX TODO: if there is something which actually requires cpanm, revert this
# (wrapped for legibility; maybe move to GNUMakefile if necessary)
# install:
#   - cpanm --quiet --installdeps --notest . ||
#     find /home/travis -name build.log -exec \
#     sh -c 'awk "/^-> N\/A$/ { n=NR } \
#           /^! Configuring .* failed\./ { e=NR } \
#           END { if (e==NR && n=e-1) exit(0); exit 1 }" "$1" ||
#        { tail -n 10000 /dev/null "$1"; false; }' _ {} \;
install: true
env:
  - secure: "RGrXObpI7D1pGIetoB6nB6mv7mxmOOWmjNv9u4sEMIh/ksyoqkLha1lMMEQdmxqojT61L8EmFm1iWjIoCSV68jNuU3d083Nq9Obbh9smwZ80S1KqszRaLIAPFuGQwLmn/ezHANh532AldydN6KKGBLQ2FhdMBEv+nTmqLS7gR/M="
script:
  - make deb && package_cloud push tripleee/procimap/debian/squeeze procimap_*_all.deb
notifications:
  email:
    - era+travis-procimap@iki.fi
