--- #YAML:1.0
meta-spec:
   version: 1.4
   url: http://module-build.sourceforge.net/META-spec-v1.4html
name: procimap
version: 0.10-5-g0384e14
abstract: Run Procmail on an IMAP mailbox
author:
  - era eriksson <era+debian@iki.fi>
resources:
  homepage: https://github.com/tripleee/procimap
  repository: git://github.com/tripleee/procimap.git
# Could not figure out how to specify a dual license ... just be less specific.
license: open_source
# XXX TODO: Maybe don't hardcode this
requires:
  Mail::IMAPClient: 0
recommends:
  Mail::IMAPClient: 3.21
