#!/usr/bin/perl -n
#
# pod2example for procimaprc distribution -- era Mon Jan  9 09:36:25 2006

use strict;
use warnings;

next if (1 .. /^\#\#\#\#\#\#\#\# procimaprc\.example starts here$/);
next if (/^\#\#\#\#\#\#\#\# procimaprc\.example ends here$/ .. eof);
print unless (/^=for example/);
